### ISSUE TITLE
NPE when click on "Check Token"

### ISSUE THREAD

**Issue by anticafe** [mikandi/kandibilling-android#2]
In demo app, I logged in with a MiKandi account but haven't any Gold or purchase yet.

After that, I click on "Check Token", then see this crash:
>04-01 15:53:00.568: E/AndroidRuntime(10467): Process: com.example.testapp, PID: 10467
04-01 15:53:00.568: E/AndroidRuntime(10467): java.lang.NullPointerException
04-01 15:53:00.568: E/AndroidRuntime(10467): 	at tools.mikandi.dev.purchasehistory.ListPurchasesReturnable.getArrayListTokens(ListPurchasesReturnable.java:111)
04-01 15:53:00.568: E/AndroidRuntime(10467): 	at tools.mikandi.dev.library.KandiLibs$4.onJSONLoaded(KandiLibs.java:416)
04-01 15:53:00.568: E/AndroidRuntime(10467): 	at tools.mikandi.dev.passreset.DefaultJSONAsyncTask.onPostExecute(DefaultJSONAsyncTask.java:31)
04-01 15:53:00.568: E/AndroidRuntime(10467): 	at tools.mikandi.dev.passreset.DefaultJSONAsyncTask.onPostExecute(DefaultJSONAsyncTask.java:1)
04-01 15:53:00.568: E/AndroidRuntime(10467): 	at android.os.AsyncTask.finish(AsyncTask.java:632)

*Edit*: I also get a crash with the same log when click on "List Purchases" button.

**Comment by MikeDocherty1991** [comment]
Do you have an email address i can email you at?

**Comment by anticafe** [comment]
Hi, mine is triet.buiminh@s3studios.asia

**Comment by MikeDocherty1991** [comment]
fixed
